const registrantList = [
    {
        id: 1,
        team: 'Human Torch',
        school: 'SMP Negeri 29 Samarinda',
        level: 'SMP/MTs Sederajat',
        time: '25/10/2025',
        status: 'Perlu Verifikasi',
        verified_by: '-',
        province: 'Kalimantan Timur',
        city: 'Samarinda',
        district: 'Samarinda Utara', // lokasi SMPN 29
    },
    {
        id: 2,
        team: 'Garuda Muda',
        school: 'SMP Negeri 89 Balikpapan',
        level: 'SMP/MTs Sederajat',
        time: '26/10/2025',
        status: 'Telah Diverifikasi',
        verified_by: 'Joko',
        province: 'Kalimantan Timur',
        city: 'Balikpapan',
        district: 'Balikpapan Selatan', // lokasi SMPN 89
    },
    {
        id: 3,
        team: 'Elang Perkasa',
        school: 'SD Negeri 087 Pontianak',
        level: 'SD/MI Sederajat',
        time: '24/10/2025',
        status: 'Perlu Verifikasi',
        verified_by: '-',
        province: 'Kalimantan Barat',
        city: 'Pontianak',
        district: 'Pontianak Kota', // SD 087 → di pusat Pontianak
    },
    {
        id: 4,
        team: 'Kijang Mata Satu',
        school: 'SMK Kesehatan Samarinda',
        level: 'SMA/SMK/MA Sederajat',
        time: '25/10/2025',
        status: 'Perlu Verifikasi',
        verified_by: '-',
        province: 'Kalimantan Timur',
        city: 'Samarinda',
        district: 'Samarinda Kota', // SMK Kesehatan Samarinda pusat
    },
    {
        id: 5,
        team: 'Ksatria Muda',
        school: 'SMP Negeri 99 Singkawang',
        level: 'SMP/MTs Sederajat',
        time: '26/10/2025',
        status: 'Ditolak',
        verified_by: 'Bambang',
        province: 'Kalimantan Barat',
        city: 'Singkawang',
        district: 'Singkawang Tengah', // sekolah SMPN 99 ada di area tengah
    },
    {
        id: 6,
        team: 'Arjuna',
        school: 'SMA Negeri 10 Balikpapan',
        level: 'SMA/SMK/MA Sederajat',
        time: '24/10/2025',
        status: 'Perlu Verifikasi',
        verified_by: '-',
        province: 'Kalimantan Timur',
        city: 'Balikpapan',
        district: 'Balikpapan Utara', // lokasi SMAN 10
    },
    {
        id: 7,
        team: 'Budiono Siregar',
        school: 'SD Negeri 1 Palangkaraya',
        level: 'SD/MI Sederajat',
        time: '25/10/2025',
        status: 'Telah Diverifikasi',
        verified_by: 'Bambang',
        province: 'Kalimantan Tengah',
        city: 'Palangkaraya',
        district: 'Pahandut', // SDN 1 Palangka Raya
    },
    {
        id: 8,
        team: 'Bina Bangsa',
        school: 'SD Negeri 77 Balikpapan',
        level: 'SD/MI Sederajat',
        time: '26/10/2025',
        status: 'Perlu Verifikasi',
        verified_by: '-',
        province: 'Kalimantan Timur',
        city: 'Balikpapan',
        district: 'Balikpapan Barat', // SDN 77
    },
    {
        id: 9,
        team: 'Ksatria Nusantara',
        school: 'SMP Nusantara Pontianak',
        level: 'SMP/MTs Sederajat',
        time: '25/10/2025',
        status: 'Telah Diverifikasi',
        verified_by: 'Joko',
        province: 'Kalimantan Barat',
        city: 'Pontianak',
        district: 'Pontianak Utara', // SMP Nusantara → di Pontianak Utara
    },
    {
        id: 10,
        team: 'Harimau Sakti',
        school: 'MAN 5 Balikpapan',
        level: 'SMA/SMK/MA Sederajat',
        time: '26/10/2025',
        status: 'Telah Diverifikasi',
        verified_by: 'Sulis',
        province: 'Kalimantan Timur',
        city: 'Balikpapan',
        district: 'Balikpapan Selatan', // lokasi MAN 5
    },
    {
        id: 11,
        team: 'Rajawali',
        school: 'SMA 1 Samarinda',
        level: 'SMA/SMK/MA Sederajat',
        time: '24/10/2025',
        status: 'Perlu Verifikasi',
        verified_by: '-',
        province: 'Kalimantan Timur',
        city: 'Samarinda',
        district: 'Samarinda Ulu', // SMAN 1 Samarinda
    },
    {
        id: 12,
        team: 'Pangeran Antasari',
        school: 'SMP 1 Banjarmasin',
        level: 'SMP/MTs Sederajat',
        time: '23/10/2025',
        status: 'Telah Diverifikasi',
        verified_by: 'Joko',
        province: 'Kalimantan Selatan',
        city: 'Banjarmasin',
        district: 'Banjarmasin Utara', // SMPN 1 Banjarmasin
    },
    {
        id: 13,
        team: 'Srikandi',
        school: 'SMK 2 Balikpapan',
        level: 'SMA/SMK/MA Sederajat',
        time: '27/10/2025',
        status: 'Perlu Verifikasi',
        verified_by: '-',
        province: 'Kalimantan Timur',
        city: 'Balikpapan',
        district: 'Balikpapan Timur', // lokasi SMKN 2 Balikpapan
    },
    {
        id: 14,
        team: 'Gatot Kaca',
        school: 'SD 1 Tenggarong',
        level: 'SD/MI Sederajat',
        time: '22/10/2025',
        status: 'Perlu Verifikasi',
        verified_by: '-',
        province: 'Kalimantan Timur',
        city: 'Kutai Kartanegara',
        district: 'Tenggarong', // SDN 1 Tenggarong
    },
    {
        id: 15,
        team: 'Panglima Burung',
        school: 'SMA 3 Pontianak',
        level: 'SMA/SMK/MA Sederajat',
        time: '27/10/2025',
        status: 'Ditolak',
        verified_by: 'Bambang',
        province: 'Kalimantan Barat',
        city: 'Pontianak',
        district: 'Pontianak Selatan', // lokasi SMAN 3 Pontianak
    },
];

export default registrantList;
